[http]
name = "kiro-api"
host = "127.0.0.1"
port = 3000
env = "dev"

[postgres]
username = "accelerator"
password = "accelerator"
host = "127.0.0.1"
port = 5432
database = "kiro"

[redis]
host = "127.0.0.1"
port = 6379

[telemetry]
name = "kiro-api"
endoint = "http://127.0.0.1:4317"
level = "info"
