[http]
env = "local"
host = "127.0.0.1"
port = 3000

[postgres]
username = "accelerator"
password = "accelerator"
host = "127.0.0.1"
port = 5432
database = "kiro"

[redis]
host = "127.0.0.1"
port = 6379

[log]
level = "info"
