[http]
name = "kiro-api"
host = "127.0.0.1"
port = 3000
env = "dev"

[postgres]
username = "accelerator"
password = "accelerator"
host = "127.0.0.1"
port = 5432
database = "kiro"

[redis]
host = "127.0.0.1"
port = 6379

[telemetry]
name = "kiro-api"
endpoint = "http://127.0.0.1:4317"
level = "info"

[jwt]
issuer = "kiro-api"
access_secret = "change-me-access-secret"
refresh_secret = "change-me-refresh-secret"
